# Java 中方法覆盖的异常处理

> 原文：<https://www.javatpoint.com/exception-handling-with-method-overriding>

如果我们谈论用异常处理覆盖方法，有很多规则。

下面列出了一些规则:

*   **如果超类方法没有声明异常**
    *   如果超类方法没有声明异常，子类覆盖方法不能声明选中的异常，但可以声明未选中的异常。
*   **如果超类方法声明了异常**
    *   如果超类方法声明了一个异常，子类覆盖的方法可以声明相同的、子类的异常或者没有异常，但是不能声明父异常。

### 如果超类方法没有声明异常

#### 规则 1:如果超类方法没有声明异常，子类覆盖的方法不能声明选中的异常。

让我们考虑以下基于上述规则的示例。

**test xceptionhild . Java**

```java

import java.io.*;  
class Parent{ 

  // defining the method 
  void msg() {
    System.out.println("parent method");
    }  
}  

public class TestExceptionChild extends Parent{  

  // overriding the method in child class
  // gives compile time error
  void msg() throws IOException {  
    System.out.println("TestExceptionChild");  
  }

  public static void main(String args[]) {  
   Parent p = new TestExceptionChild();  
   p.msg();  
  }  
}  

```

**输出:**

![Exception Handling with Method Overriding in Java](../img/b63d62af153525607e30af66bf725263.png)

#### 规则 2:如果超类方法没有声明异常，子类覆盖的方法不能声明选中的异常，但是可以声明未选中的异常。

**test xceptionhild 1 . Java**

```java

import java.io.*;  
class Parent{  
  void msg() {
    System.out.println("parent method");
  }  
}  

class TestExceptionChild1 extends Parent{  
  void msg()throws ArithmeticException {  
    System.out.println("child method");  
  }  

  public static void main(String args[]) {  
   Parent p = new TestExceptionChild1();  
   p.msg();  
  }  
} 

```

**输出:**

![Exception Handling with Method Overriding in Java](../img/e69d65c3b48a3eb1a523c12ec353f898.png)

### 如果超类方法声明了异常

#### 规则 1:如果超类方法声明了一个异常，子类覆盖的方法可以声明同一个子类异常或者没有异常，但是不能声明父异常。

### 子类覆盖方法声明父异常的例子

**test xceptionhild 2 . Java**

```java

import java.io.*;  
class Parent{  
  void msg()throws ArithmeticException {
    System.out.println("parent method");
  }  
}  

public class TestExceptionChild2 extends Parent{  
  void msg()throws Exception {
    System.out.println("child method");
  }  

  public static void main(String args[]) {  
   Parent p = new TestExceptionChild2();  

   try {  
   p.msg();  
   }
   catch (Exception e){} 

  }  
}   

```

**输出:**

![Exception Handling with Method Overriding in Java](../img/d087352747e7e062983c566631eb5dbd.png)

### 子类覆盖方法声明相同异常的例子

**test xceptionhild 3 . Java**

```java

import java.io.*;  
class Parent{  
  void msg() throws Exception {
    System.out.println("parent method");
  }  
}  

public class TestExceptionChild3 extends Parent {  
  void msg()throws Exception {
    System.out.println("child method");
  }  

  public static void main(String args[]){  
   Parent p = new TestExceptionChild3();  

   try {  
   p.msg();  
   }
   catch(Exception e) {}  
  }  
}  

```

**输出:**

![Exception Handling with Method Overriding in Java](../img/6550a6d903a6391c4f54991fd8198231.png)

### 子类覆盖方法声明子类异常的例子

**test xceptionhild 4 . Java**

```java

import java.io.*;  
class Parent{  
  void msg()throws Exception {
    System.out.println("parent method");
  }  
}  

class TestExceptionChild4 extends Parent{  
  void msg()throws ArithmeticException {
    System.out.println("child method");
  }  

  public static void main(String args[]){  
   Parent p = new TestExceptionChild4();  

   try {  
   p.msg();  
   }
   catch(Exception e) {}  
  }  
}  

```

**输出:**

![Exception Handling with Method Overriding in Java](../img/5fa92035c4c08ec78d4b34d6603c2ff8.png)

### 子类覆盖方法没有声明异常的情况下的示例

**test xceptionhild 5 . Java**

```java

import java.io.*;  
class Parent {  
  void msg()throws Exception{
    System.out.println("parent method");
  }  
}  

class TestExceptionChild5 extends Parent{  
  void msg() {
    System.out.println("child method");
  }  

  public static void main(String args[]){  
   Parent p = new TestExceptionChild5();  

   try {  
   p.msg();  
   }
   catch(Exception e) {}

  }  
}   

```

**输出:**

![Exception Handling with Method Overriding in Java](../img/bdcc4fca47931173f86d863ee3ae8df3.png)

* * *